name: azureml-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - azureml-defaults
      - python-dotenv
      - numpy
      - scipy
      - pandas
      - scikit-learn
      - tensorflow
      - keras